import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import odeint
from util.config import t, step, num_traj

from trajectory.velocity import velocity
from trajectory.init_dist import init_dist

# Distribution of initial data [q0_ph, q0_el] where both are arrays of values generated by normal distribution
dist = init_dist()

for i in range(num_traj):
    q0 = [dist[0][0][i-1], dist[1][0][i-1]]
    time = np.linspace(0, t, step)

    traj = np.transpose(odeint(velocity, q0, time))

    plt.plot(traj[0], time, traj[1], time)

plt.show()
